//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Security
{
    using System;
    using System.Collections.Generic;
    
    public partial class permission
    {
        public long ID_permission { get; set; }
        public long ID_user { get; set; }
        public long ID_module { get; set; }
        public bool status { get; set; }
    
        public virtual module module { get; set; }
        public virtual user user { get; set; }
    }
}
